apiVersion: autoscaling.aws.m.upbound.io/v1beta1
kind: AutoscalingGroup
metadata:
  name: asg-blue
spec: 
  forProvider:
    minSize: 1
    maxSize: 3
    region: us-east-1
    launchTemplate: 
      name: httpd-launch-template
    availabilityZones: 
      - "us-east-1d"
  providerConfigRef:
    name: default
    kind: ClusterProviderConfig
