apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: Instance
metadata:
  name: ec2-instance-1
  namespace: demo
spec:
  forProvider:
    ami: ami-0b09ffb6d8b58ca91
    availabilityZone: us-east-1d
    instanceType: t3.micro
    region: us-east-1
  providerConfigRef:
    name: default
    kind: ProviderConfig
---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: LaunchTemplate
metadata:
  name: ec2-launch-template-1
  namespace: demo
  labels: 
    template: template1
spec:
  forProvider:
    ImageId: ami-0b09ffb6d8b58ca91
    blockDeviceMappings:
        - deviceName: /dev/sda1
          ebs:
            volumeSize: 20
    instanceType: t3.micro
    region: us-east-1
  providerConfigRef:
    name: default
    kind: ProviderConfig
