apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: Instance
metadata:
  name: ec2-instance-1
  namespace: default
spec:
  forProvider:
    ami: ami-0b09ffb6d8b58ca91
    availabilityZone: us-east-1d
    instanceType: t3.micro
    region: us-east-1
