apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: LaunchTemplate
metadata:
  name: test-crossplane-obj
spec:
  forProvider:
    launchTemplateData:
      keyName: kube
      tagSpecifications:
        - resourceType: volume
          tags:
            - key: original
              value: "1"
    launchTemplateName: test-crossplane-obj
    region: us-east-1
  providerConfigRef:
    name: example
