apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata: 
  name: kristian-bucket-crossplane
  labels:
    testing.upbound.io/example-name: s3
spec:
  forProvider:
    region: us-east-1
    tags:
      foo: bar
