apiVersion: v1
kind: Secret
metadata: 
  name: aws-secrets 
  namespace: crossplane-system
type: Opaque
data:
  aws_access_key_id: aws-access-key-id.txt
  aws_secret_access_key: aws-secret-access-key.txt
