apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name:  xs3.crossplane.io
spec:
  scope: Namespaced
  group: xs3s.crossplane.io
  names: 
    kind: XS3
    plural: xs3s
  versions: 
  - name: v1alpha1
    served: true
    referenceable: true
    schema: 
      openAPIV3Schema: 
        type: object
        properties:
          spec:   
            type: object 
            properties:
              bucket-name: 
                type: string
              region:
                type: string
              required:
                - bucket-name
                - region
