apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name:  apps.example.crossplane.io
spec:
  scope: Namespaced
  group: example.crossplane.io
  names: 
    kind: XDeploy
    plural: xdeploys
  versions: 
  - name: v1alpha1
    schema: 
      openAPIV3Schema: 
        type: object
        properties:
          spec:   
            type: object 
            properties: 
              region:
                type: string
