apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name:  xs3.crossplane.io
spec:
  scope: Namespaced
  group: xs3s.crossplane.io
  names: 
    kind: XS3
    plural: xs3s
  versions: 
  - name: v1alpha1
    schema: 
      openAPIV3Schema: 
        type: object
        properties:
          spec:   
            type: object 
            properties: 
              region:
                type: string
