apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: Instance
metadata:
  name: ec2-instance-1
  namespace: demo
spec:
  forProvider:
    region: us-east-1
    ImageId: ami-0b09ffb6d8b58ca91
    instanceType: t3.micro
    region: us-east-1
    availabilityZone: us-east-1a
    subnetId: subnet-00f9e75248e1091fe
    associatePublicIpAddress: true 
    vpcSecurityGroupIds: 
     - sg-0155765612c29da07
  providerConfigRef:
    name: default
    kind: ProviderConfig
---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: LaunchTemplate
metadata:
  name: ec2-launch-template-1
  namespace: demo
  labels: 
    template: template-1
spec:
  forProvider:
    name: template-1
    imageId: ami-0b09ffb6d8b58ca91
    instanceType: t3.micro
    region: us-east-1
    securityGroupNameSelector:
      matchLabels:
        testing.upbound.io/elb: elbv2
    userData: "IyEvYmluL2Jhc2gKIyBVc2UgdGhpcyBmb3IgeW91ciB1c2VyIGRhdGEgKHNjcmlwdCBmcm9tIHRvcCB0byBib3R0b20pCiMgaW5zdGFsbCBodHRwZCAoTGludXggMiB2ZXJzaW9uKQp5dW0gdXBkYXRlIC15Cnl1bSBpbnN0YWxsIC15IGh0dHBkCnN5c3RlbWN0bCBzdGFydCBodHRwZApzeXN0ZW1jdGwgZW5hYmxlIGh0dHBkCmVjaG8gIjxoMT5IZWxsbyBXb3JsZCBmcm9tICQoaG9zdG5hbWUgLWYpPC9oMT4iID4gL3Zhci93d3cvaHRtbC9pbmRleC5odG1sCg=="
  providerConfigRef:
    name: default
    kind: ProviderConfig
