apiVersion: elbv2.aws.m.upbound.io/v1beta1
kind: LB
metadata:
  name: lb-1
  namespace: demo
  labels:
    testing.upbound.io/elb: elbv2
spec:
  forProvider:
    subnetSelector:
      matchLabels:
        testing.upbound.io/elb: elbv2
    loadBalancerType: application
    name: lb-1
    region: us-east-1  
    securityGroupSelector:
      matchLabels:
        testing.upbound.io/elb: elbv2
  providerConfigRef:
    name: default
    kind: ProviderConfig
---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: VPC
metadata:
  name: vpc-1
  namespace: demo
  labels:
    testing.upbound.io/elb: elbv2
spec:
  forProvider:    
    cidrBlock: 172.16.0.0/16
    region: us-east-1  
  providerConfigRef:
    name: default
    kind: ProviderConfig
status:
    atProvider:
      defaultSecurityGroupId: "securityGroupId-1"
---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: InternetGateway
metadata:
  name: internet-gateway-1
  namespace: demo
  labels:
    testing.upbound.io/elb: elbv2
spec:
  forProvider:
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/elb: elbv2
    region: us-east-1
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/elb: elbv2
  providerConfigRef:
    name: default
    kind: ProviderConfig
---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: Subnet
metadata:
  name: subnet-1
  namespace: demo
  labels:
    testing.upbound.io/elb: elbv2
spec:
  providerConfigRef:
    name: default
    kind: ProviderConfig
  forProvider:
    availabilityZone: us-east-1a
    cidrBlock: 172.16.10.0/24
    region: us-east-1
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/elb: elbv2
---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: Subnet
metadata:
  name: subnet-2
  namespace: demo
  labels:
    testing.upbound.io/elb: elbv2
spec:
  providerConfigRef:
    name: default
    kind: ProviderConfig
  forProvider:
    availabilityZone: us-east-1b
    cidrBlock: 172.16.20.0/24
    region: us-east-1
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/elb: elbv2
---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  name: securitygroup-1
  namespace: demo
  labels:
    testing.upbound.io/elb: elbv2
spec:
  providerConfigRef:
    name: default
    kind: ProviderConfig
  forProvider:
    description: Allow TLS inbound traffic
    name: allow_tls
    region: us-east-1
    tags:
      Name: east
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/elb: elbv2
---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: SecurityGroupIngressRule
metadata:
  name: securitygroup-rule-1
  namespace: demo
  labels:
    testing.upbound.io/elb: elbv2
spec:
  providerConfigRef:
    name: default
    kind: ProviderConfig  
  forProvider:
    fromPort: 80
    toPort: 80
    ipProtocol: 'tcp' 
    region: us-east-1
    referencedSecurityGroupIdSelector:
      matchLabels:
        testing.upbound.io/elb: elbv2
    securityGroupIdSelector:
      matchLabels:
        testing.upbound.io/elb: elbv2                
---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: SecurityGroupEgressRule
metadata:
  name: securitygroup-rule-2
  namespace: demo
  labels:
    testing.upbound.io/elb: elbv2
spec:
  providerConfigRef:
    name: default
    kind: ProviderConfig  
  forProvider:
    fromPort: 80
    toPort: 80
    ipProtocol: 'tcp' 
    region: us-east-1
    referencedSecurityGroupIdSelector:
      matchLabels:
        testing.upbound.io/elb: elbv2
    securityGroupIdSelector:
      matchLabels:
        testing.upbound.io/elb: elbv2        
     

