apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata: 
  name: xs3s.example.org  
spec:
  scope: LegacyCluster
  group: example.org
  names: 
    kind: Xs3
    plural: xs3s
  claimNames:
    kind: Xs3Claim
    plural: xs3claims
  defaultCompositeDeletePolicy: Background
  versions:
  - name: v1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              region:
                type: string
              name: 
                type: string
              namespace:
                type: string
            required:
              - namespace
              - name
              - region
              